### ISSUE TITLE
Not working with python 3.9

### ISSUE THREAD

**Issue by sparse91** [sdgathman/pysrs#10]
```AttributeError: module 'base64' has no attribute 'encodestring'.```
I know this fixed in master but when will it be released?

**Comment by sdgathman** [comment]
Pushed 1.0.4 tag.  Not tested as I would like on python3, so please report bugs.
